### ISSUE TITLE
Suggestion: TypeScript typings to Reason bindings transformer

### ISSUE THREAD

**Issue by niieani** [BuckleTypes/reason-js#1]
Instead of doubling the effort in re-creating the DOM bindings it might be simpler to transform the AST of TypeScript definitions into Reason bindings. The added benefit would be that such a transformer would be universal - given the huge number of good quality typings available for TypeScript, Reason could quickly become a hugely popular alternative to it, especially given the BuckleScript 1.0 release and the fantastic benefits it offers over TS.

Thoughts?

**Comment by chenglou** [comment]
Welp, the magic of the js community happened. @glennsl basically hand-made the whole bindings and rendered this issue somewhat obsolete, lol.

We can keep the conversation going in another place, like bucklescript. Also, this repo's bindings fixes some of TypeScript's invalid definitions, and parts that'd convert to slightly awkward idioms. Example of tricks we can pull off: https://github.com/BuckleTypes/reason-js/issues/28
