### ISSUE TITLE
Mysterious error with `-make-world`

### ISSUE THREAD

**Issue by solidsnack** [BuckleTypes/reason-js#20]
```
:;  node_modules/.bin/bsb -make-world
    Regenerating build spec : File not found
    Fatal error: exception Sys_error("tests/fetch: No such file or directory")
    Error happened when running command .../reason-js/node_modules/bs-platform/bin/bsb.exe with args [ '-make-world' ]
```

It seems like it's looking for the directory structure in `src/` to be mirrored in `tests/`.

```
:;  cp -a src/fetch/ tests/fetch/
:;  node_modules/.bin/bsb -make-world
    Regenerating build spec : File not found
    Fatal error: exception Sys_error("tests/gl: No such file or directory")
    Error happened when running command /Users/solidsnack/Downloads/reason-js/node_modules/bs-platform/bin/bsb.exe with args [ '-make-world' ]
```

How does the `.re` code get translated to `.ml`?

**Comment by glennsl** [comment]
Sorry! Latest bs must have changed how bsb handles directory traversal. #21 should fix it, could you make the same change locally and test?

**Comment by glennsl** [comment]
And to answer your last question, refmt is used to translate `.re` to `.ml`. bsb passes refmt to the compiler as a preprocessor, which the compiler then uses to reformat the code on the fly as it compiles. It's pretty cool.

**Comment by solidsnack** [comment]
The level of integration is really surprising. I thought I was going to have to build a monstrous build chain.

**Comment by solidsnack** [comment]
Thank you for your patch.

**Comment by glennsl** [comment]
No problem! It's a pretty smooth experience unless you need to pull packages from both opam and npm. But I believe that's about to be sorted out as well. Reason is about the whole ecosystem and developer experience, not just the syntax or language. And it's looking real good from where I'm standing.
