### ISSUE TITLE
Should experimental APIs return Js.undefined <whatever>?

### ISSUE THREAD

**Issue by glennsl** [BuckleTypes/reason-js#26]
So their presence can actually be checked for before they're used.

**Comment by chenglou** [comment]
@glennsl is this still relevant?

**Comment by glennsl** [comment]
This is an ill defined problem description, but it's not solved is it? There's still no way to detect if a feature is available before it's used? Maybe this isn't something we should care about?

**Comment by chenglou** [comment]
What about http://bloomberg.github.io/bucklescript/Manual.html#_detect_global_variable_existence_code_bs_external_code_since_1_5_1

**Comment by glennsl** [comment]
Hmm, yes that's certainly better than this proposal :) Closing.
