### ISSUE TITLE
What should the naming convention for abbreviations be?

### ISSUE THREAD

**Issue by glennsl** [BuckleTypes/reason-js#30]
Due to OCaml's rules for which identifiers can be lower case and upper case, the current convention is PascalCase/camelCase, e.g. "Html", "Json", "dom" etc.

Should it be "DOM"/"dom", "JSON"/"json" instead? How would that work with module fiilenames? Should it be e.g. "jsonRe.re", it would then have to be used internally as "JsonRe" and be exported as "module JSON = JsonRe".

**Comment by chenglou** [comment]
Filenames absolutely have to start with a lower-case, for case-sensitive fs: https://github.com/bloomberg/bucklescript/issues/913#issuecomment-259964510

So `jSON.re` would kinda be awkward. `json.re` it is.

We can keep the current `module Json = JsonRe`, etc.
