### ISSUE TITLE
Invalid referrer policy when using `fetchWithInit`

### ISSUE THREAD

**Issue by dwwoelfel** [BuckleTypes/reason-js#44]
When using the [fetchWithInit example](https://github.com/BuckleTypes/reason-js/blob/master/examples/fetch_example.re#L11), I get an error from the browser: `TypeError: Failed to execute 'fetch' on 'Window': Invalid referrer policy`

According to the [spec](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy), referrerPolicy should never be undefined. 

Adding None as the referrerPolicy works:

```
Fetch.RequestInit.make method_::Post referrerPolicy::None ();
```

**Comment by dwwoelfel** [comment]
There's a similar problem with `integrity`. It should also default to an empty string instead of undefined (or, even better, remove the key from the object).

**Comment by glennsl** [comment]
Hi @dwwoelfel . Thanks for reporting! There are unfortunately limitations or bugs in BuckleScript that currently prevents me from not setting the properties, but we can at least provide better defaults. Could you verify that #46 fixes your problem?
